version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - "27017"
  vacation:
    image: tooling/tooling-vacation
    expose:
        - "8080"
    links:
      - mongo
    depends_on:
      - mongo
  project:
    image: tooling/tooling-project
    expose:
        - "8080"
    links:
      - mongo
    depends_on:
      - mongo
  activity:
    image: tooling/tooling-activity
    expose:
        - "8080"
    links:
      - mongo
    depends_on:
      - mongo
  api:
    image: tooling/tooling-zuul
    ports:
        - 8080:8080
    links:
      - mongo
      - vacation
      - project
    depends_on:
      - mongo