zuul:
  routes:
    vacations:
      url: http://vacation
    projects:
      url: http://project

ribbon:
  eureka:
    enabled: false

server:
  port: 8080

tooling:
  security:
    rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGn33BTDWnQ3NeM71JKhAKN2k0fpLim7O5BdxaGlhU0sU+SBinFZ9csasEbe4YdIbBrMuO/5VP7wbpzJYVxpAJWBnZs3qnYEL5O+tfBjKePb4y+hhROQLQKtAodFwjLOP6p/WIuepJqn7tFqQahYGEHBBX11Mn+GopqWLq6d+AdQIDAQAB
    rsaPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIaffcFMNadDc14zvUkqEAo3aTR+kuKbs7kF3FoaWFTSxT5IGKcVn1yxqwRt7hh0hsGsy47/lU/vBunMlhXGkAlYGdmzeqdgQvk7618GMp49vjL6GFE5AtAq0Ch0XCMs4/qn9Yi56kmqfu0WpBqFgYQcEFfXUyf4aimpYurp34B1AgMBAAECgYBOhBDlPxx/zGAqDgUU+fpW6xBp9HSYw/TjMZ7d0kW4WyF8/LGcKYlDl7/FmpPmIXhC1xP19+zOrPscOx1B4Ag6+sW+DXIyhZptMVq3Obk6ywYbMtzlHF4PWI7sE+spPlFOj4ho6n2U2hCko5HGrV6kc4jrUe5rBHc7lD5llMfMVQJBAPHQkKLrs1gpOh+1/KUIEPyg7YBsoBm7hm4npG8bx+z/nIiVLTDZAoIpFPkIIv364zIK5wc+0cz4N0pxMPHRmWsCQQCOhS7DHqtTErqXP+b5dxZ4yPKpEYqhMjgxI9pyVST/DmOKvPYfORRCNhfZFzTnl96GC2wsI4wLpL2XUU0t/mWfAkBWfcQOEgIu6WgZyY0ZNj5lLeZlRfUp3xIhOlqtRyGGWpMRo1Hro+MqzSjsPgXOFDvJPW8O/2ApUSrtnHjmNZMLAkA1lEA2PotuGbZoMi/lTS33jqQbh2q0myqg3re7D+Nut7wYZl2o8054bdmdVaof/uo7PoQWO+7kWbSk9H2tctxFAkEAhWW5erTSP8k/5SwLhINr4vikgOeOqSTsLFBp81+ZBPa01r/JT2ZLK3H4mK1AsF19TCOqCa03xjQ9+ZnSNXETFg==

spring:
  data:
    mongodb.uri: mongodb://mongo/tooling

